# 服务端口
server:
  port: 8202
spring:
  application:
    name: service-cmn
  profiles:
    # 环境设置：dev、test、prod
    active: dev
  datasource:
    # mysql数据库连接
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.44.165:3306/yygh_cmn?characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345
    #  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
